project                  = "cwb07-prod-b74b"
project_prefix           = "cwb07"
region                   = "us-west1"
environment              = "prod"
user_management_base_url = "https://api.cwb07.dsgov.demo.nuvalence.io/um"
