timeout: 1200s
logsBucket: "gs://${_ARTIFACT_BUCKET_NAME}/cloudbuild-logs/app-${_SERVICE_NAME}-pull-request-trigger"
steps:
  - id: "install"
    name: "node:$_NODE_VERSION"
    entrypoint: "npm"
    args: ["install"]
  - id: "license-check"
    name: "node:$_NODE_VERSION"
    entrypoint: "npm"
    args: ["run", "license-check"]
  - id: "build"
    name: "node:$_NODE_VERSION"
    entrypoint: "npm"
    args: ["run", "gcp-build"]
